import type { Event, Ticket } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const events: Event[] = [
  {
    id: 'music-fest-2024',
    name: 'Campus Music Fest 2024',
    description: 'An electrifying night of music featuring student bands and local artists.',
    longDescription: 'Join us for the biggest musical event of the year! Campus Music Fest 2024 brings together a diverse lineup of genres, from rock and pop to electronic and folk. Enjoy live performances, food trucks, and an unforgettable atmosphere under the stars. All proceeds go to the student arts fund.',
    date: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    venue: 'Main Quad',
    price: 15.0,
    committee: 'Music Committee',
    tags: ['Music', 'Concert', 'Festival'],
    image: PlaceHolderImages['event-music-concert'],
  },
  {
    id: 'tech-innovators-conference',
    name: 'Tech Innovators Conference',
    description: 'Explore the future of technology with talks from industry leaders.',
    longDescription: 'Dive deep into the world of AI, blockchain, and quantum computing. Our annual Tech Innovators Conference connects students with pioneers from leading tech companies. The event includes keynote speeches, interactive panels, and networking sessions. A must-attend for aspiring technologists.',
    date: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString(),
    venue: 'Engineering Auditorium',
    price: 5.0,
    committee: 'Computer Science Society',
    tags: ['Technology', 'Conference', 'AI'],
    image: PlaceHolderImages['event-tech-conference'],
  },
  {
    id: 'art-in-bloom-exhibition',
    name: 'Art in Bloom Exhibition',
    description: 'A stunning exhibition of paintings, sculptures, and digital art by our talented students.',
    longDescription: 'Experience the creativity of our campus community at the "Art in Bloom" exhibition. This curated showcase features a wide range of artistic expressions. Meet the artists, discuss their work, and even purchase pieces to support their journey. Refreshments will be served.',
    date: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    venue: 'Fine Arts Gallery',
    price: 0,
    committee: 'Fine Arts Club',
    tags: ['Art', 'Exhibition', 'Culture'],
    image: PlaceHolderImages['event-art-exhibition'],
  },
  {
    id: 'hackathon-infinity',
    name: 'Hackathon: Infinity',
    description: 'A 24-hour challenge to build innovative projects and win amazing prizes.',
    longDescription: 'Code, create, and collaborate at Hackathon: Infinity! Teams of up to four will have 24 hours to develop a software or hardware project from scratch. Mentors from the industry will be available to guide you. All skill levels are welcome. Food, drinks, and swag provided!',
    date: new Date(new Date().setDate(new Date().getDate() + 40)).toISOString(),
    venue: 'Innovation Hub',
    price: 0,
    committee: 'Coding Club',
    tags: ['Hackathon', 'Coding', 'Technology'],
    image: PlaceHolderImages['event-hackathon'],
  },
    {
    id: 'annual-sports-gala',
    name: 'Annual Sports Gala',
    description: 'Compete and cheer in a day full of exciting sports competitions.',
    longDescription: 'The Annual Sports Gala is here! Represent your department in various sports including soccer, basketball, track and field, and more. A day of friendly competition, team spirit, and athletic excellence. Medals and trophies for the winners.',
    date: new Date(new Date().setDate(new Date().getDate() + 15)).toISOString(),
    venue: 'Campus Sports Complex',
    price: 0,
    committee: 'Athletics Department',
    tags: ['Sports', 'Competition', 'Health'],
    image: PlaceHolderImages['event-sports-day'],
  },
  {
    id: 'robotics-bootcamp',
    name: 'Robotics Bootcamp',
    description: 'A hands-on workshop to build and program your first robot.',
    longDescription: 'Ever wanted to build a robot? This is your chance! Our Robotics Bootcamp is a beginner-friendly workshop where you will learn the basics of electronics, mechanics, and programming. All components and kits will be provided. No prior experience necessary.',
    date: new Date(new Date().setDate(new Date().getDate() + 18)).toISOString(),
    venue: 'Mechatronics Lab',
    price: 25.0,
    committee: 'Robotics Club',
    tags: ['Workshop', 'Robotics', 'STEM'],
    image: PlaceHolderImages['event-robotics-workshop'],
  },
  {
    id: 'lit-fest-2024',
    name: 'Literary Fest 2024',
    description: 'A celebration of words, stories, and ideas with famous authors.',
    longDescription: 'Immerse yourself in the world of literature at LitFest 2024. This two-day festival features author talks, book signings, poetry slams, and panel discussions on contemporary writing. A paradise for book lovers and aspiring writers.',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    venue: 'Central Library',
    price: 10.0,
    committee: 'Literary Society',
    tags: ['Literature', 'Festival', 'Books'],
    image: PlaceHolderImages['event-literary-fest'],
  },
  {
    id: 'startup-career-fair',
    name: 'Startup Career Fair',
    description: 'Connect with innovative startups and find your next big opportunity.',
    longDescription: 'Looking for an exciting internship or full-time role? The Startup Career Fair brings over 50 fast-growing startups to campus. Network with founders, learn about different industries, and land your dream job in the startup ecosystem.',
    date: new Date(new Date().setDate(new Date().getDate() + 50)).toISOString(),
    venue: 'Grand Ballroom',
    price: 0,
    committee: 'Entrepreneurship Cell',
    tags: ['Career', 'Networking', 'Startups'],
    image: PlaceHolderImages['event-career-fair'],
  },
];

export const tickets: Ticket[] = [
  {
    id: 'tkt-001',
    event: events[0],
    studentName: 'Alex Johnson',
    qrCodeUrl: `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=tkt-001-${events[0].id}`,
  },
  {
    id: 'tkt-002',
    event: events[2],
    studentName: 'Alex Johnson',
    qrCodeUrl: `https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=tkt-002-${events[2].id}`,
  },
];
